# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:latest

pipelines:
  branches:
    master:
      - step:
          name: Iniciando Deploy
          deployment: staging
          script:
            - cat ./deploy.sh | ssh root@191.101.70.52
            - echo "Deploy step finished"

